1. 基础预备知识的实现

In [7]:
import torch

In [8]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
x.shape

torch.Size([12])

In [10]:
x.numel()

12

In [14]:
X = x.reshape(2, 6)
X

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

可以自动计算维度，可以用x.reshape(-1,4)或x.reshape(3,-1)来取代x.reshape(3,4)

In [15]:
torch.zeros((2,3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [16]:
torch.ones((3, 5, 1))

tensor([[[1.],
         [1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.],
         [1.]]])

In [17]:
torch.randn(3, 4)

tensor([[ 1.8102, -1.7587, -0.9469, -0.0841],
        [-1.0363, -0.0848,  1.4233,  1.5191],
        [ 0.1873, -1.8784,  0.8196, -1.7779]])

- 为什么上面赋0，赋1有两个括号？
因为上面其实是两步，先生成张量，再对张量进行赋0或1的操作。这里只有随机生成张量的操作。

In [24]:
x = torch.tensor([[3, 4, 5], [7, 8, 9], [10, 11, 12]])
x
x.shape

torch.Size([3, 3])

In [26]:
x = torch.tensor([3, 4, 5, 6])
y = torch.tensor([7, 8, 9, 10])
x + y, x - y, x * y, x / y, x ** y # **运算是幂运算

(tensor([10, 12, 14, 16]),
 tensor([-4, -4, -4, -4]),
 tensor([21, 32, 45, 60]),
 tensor([0.4286, 0.5000, 0.5556, 0.6000]),
 tensor([    2187,    65536,  1953125, 60466176]))

In [27]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

dim=0是沿行方向相连接，dim=1是沿列方向相连接。

In [28]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [29]:
X.sum()

tensor(66.)

In [30]:
a = torch.arange(4).reshape(1, -1)
b = torch.arange(8).reshape(2, -1)
a, b

(tensor([[0, 1, 2, 3]]),
 tensor([[0, 1, 2, 3],
         [4, 5, 6, 7]]))

In [31]:
a + b

tensor([[ 0,  2,  4,  6],
        [ 4,  6,  8, 10]])

广播机制可以理解为，缺行行复制，缺列列复制。比如上述a, b张量，一个是1x4， 一个是2x4，最后的结果应该是2x4，所以第一个矩阵行复制。

In [32]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [33]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

注意，python中的索引下标都是从0开始的，不是从1。所以上面代码修改的是第二行，第三列的元素。

In [34]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

注意，上述切片操作中，[0:2]表示的是第0行和第1行，是不包括第2行的！！！

In [35]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [36]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

矩阵的转置

In [37]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

怎么理解下面的张量？可以理解为2个3x4的矩阵堆叠在一起了。

- 为什么不是4个2x3的矩阵堆叠在一起？
这和reshape的格式有关系。和张量的结构方式有关系。由于第一个写的是2，所以被分成了2块。

In [38]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

修改一下就变成4个2x3的矩阵了

In [40]:
X = torch.arange(24).reshape(4, 2, 3)
X

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]])